services:
  test-py311:
    build:
      context: .
      dockerfile: container/Containerfile.dev
      args:
        PYTHON_VERSION: "3.11"
    volumes:
      - ./dsmr_parser:/app/dsmr_parser
      - ./test:/app/test
      - tox-cache-311:/app/.tox
    command: tox

  test-py312:
    build:
      context: .
      dockerfile: container/Containerfile.dev
      args:
        PYTHON_VERSION: "3.12"
    volumes:
      - ./dsmr_parser:/app/dsmr_parser
      - ./test:/app/test
      - tox-cache-312:/app/.tox
    command: tox

  test-py313:
    build:
      context: .
      dockerfile: container/Containerfile.dev
      args:
        PYTHON_VERSION: "3.13"
    volumes:
      - ./dsmr_parser:/app/dsmr_parser
      - ./test:/app/test
      - tox-cache-313:/app/.tox
    command: tox

  test-py314:
    build:
      context: .
      dockerfile: container/Containerfile.dev
      args:
        PYTHON_VERSION: "3.14"
    volumes:
      - ./dsmr_parser:/app/dsmr_parser
      - ./test:/app/test
      - tox-cache-314:/app/.tox
    command: tox

volumes:
  tox-cache-311:
  tox-cache-312:
  tox-cache-313:
  tox-cache-314:
